"""
api.py — FastAPI Backend for AI RPG World Generator
=====================================================
Exposes the world generator as a REST API endpoint.
Demonstrates how the ML model integrates into a game backend service.

Start the server:
    uvicorn api:app --reload

Then visit:
    http://127.0.0.1:8000/docs         ← Interactive Swagger UI
    http://127.0.0.1:8000/generate_world?theme=fantasy
"""

from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from generate import generate_world, THEME_CONFIGS

# ── App setup ─────────────────────────────────────────────────────────────────
app = FastAPI(
    title="AI RPG World Generator API",
    description=(
        "A FastAPI backend powered by DistilGPT2 that generates procedural "
        "RPG world scenarios through prompt engineering. "
        "Demonstrates ML model integration into a game backend service."
    ),
    version="1.0.0",
)


# ── Response schema ────────────────────────────────────────────────────────────
class WorldResponse(BaseModel):
    """Schema for a generated RPG world response."""
    theme: str
    temperature: float
    max_length: int
    seed: int | None
    world: str


# ── Endpoints ─────────────────────────────────────────────────────────────────

@app.get("/", summary="Health check")
def root():
    """Health-check endpoint — confirms the API is live."""
    return {
        "status": "online",
        "message": "AI RPG World Generator API is running.",
        "docs": "/docs",
        "available_themes": list(THEME_CONFIGS.keys()),
    }


@app.get("/generate_world", response_model=WorldResponse, summary="Generate an RPG world")
def generate_world_endpoint(
    theme: str = Query(
        default="fantasy",
        description="World theme",
        enum=list(THEME_CONFIGS.keys()),
    ),
    temperature: float = Query(
        default=0.8,
        ge=0.1,
        le=2.0,
        description="Sampling temperature — controls creativity (0.1 = structured, 2.0 = chaotic)",
    ),
    max_length: int = Query(
        default=250,
        ge=50,
        le=500,
        description="Maximum tokens to generate",
    ),
    seed: int | None = Query(
        default=None,
        description="Random seed for reproducibility (omit for random output)",
    ),
):
    """
    Generate a complete RPG world scenario.

    Returns a structured world with World Name, Description, NPC, Quest,
    Reward Item, and Lore — all generated by DistilGPT2 via prompt engineering.
    """
    try:
        world_text = generate_world(
            theme=theme,
            temperature=temperature,
            max_length=max_length,
            seed=seed,
        )
        return WorldResponse(
            theme=theme,
            temperature=temperature,
            max_length=max_length,
            seed=seed,
            world=world_text,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Generation failed: {str(e)}")


@app.get("/themes", summary="List available world themes")
def list_themes():
    """Return all supported world themes."""
    return {"themes": list(THEME_CONFIGS.keys())}
